[package]
name = "script-bench"
version = "0.1.0"
edition = "2021"
authors = ["Aleksandr Orlenko <zxteam@pm.me>"]

[features]
mlua_lua54 = ["mlua/lua54", "mlua/vendored"]
mlua_luau = ["mlua/luau-jit"]

[dependencies]
rand = "0.8"
mlua = { version = "0.9.0-rc.3", optional = true }
rlua = { version = "0.19.7", optional =  true }
rhai = { version = "1.15.1", optional = true }
rune = { version = "0.12.4", optional = true }
itertools = "0.11"

[dev-dependencies]
criterion = { version = "0.5" }

[profile.bench]
lto = true

[[bench]]
name = "mlua_lua54"
harness = false
required-features = ["mlua_lua54"]

[[bench]]
name = "mlua_luau"
harness = false
required-features = ["mlua_luau"]

[[bench]]
name = "rlua"
harness = false
required-features = ["rlua"]

[[bench]]
name = "rhai"
harness = false
required-features = ["rhai"]

[[bench]]
name = "rune"
harness = false
required-features = ["rune"]
