[package]
name = "script-bench"
version = "0.1.0"
edition = "2021"
authors = ["Aleksandr Orlenko <zxteam@pm.me>"]

[lib]
name = "script_bench"

[features]
mlua_lua54 = ["mlua/lua54", "mlua/vendored"]
mlua_luau = ["mlua/luau-jit"]
rhai = ["dep:rhai", "dep:itertools", "dep:anyhow"]
rune = ["dep:rune", "dep:anyhow"]

[dependencies]
rand = "0.8"
anyhow = { version = "1.0", optional = true }
itertools = { version = "0.12", optional = true }
mlua = { version = "0.9.6", optional = true }
rhai = { version = "1.17.1", optional = true }
rune = { version = "0.13.2", optional = true }

[dev-dependencies]
criterion = { version = "0.5" }

[profile.bench]
lto = true

[[bench]]
name = "mlua_lua54"
harness = false
required-features = ["mlua_lua54"]

[[bench]]
name = "mlua_luau"
harness = false
required-features = ["mlua_luau"]

[[bench]]
name = "rhai"
harness = false
required-features = ["rhai"]

[[bench]]
name = "rune"
harness = false
required-features = ["rune"]
